[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gen-hack"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cartopy>=0.25.0",
    "cftime>=1.6.5",
    "contextily>=1.7.0",
    "dash>=3.3.0",
    "dash-bootstrap-components>=1.6.0",
    "dask>=2025.12.0",
    "esda>=2.8.0",
    "folium>=0.20.0",
    "geopandas>=1.1.2",
    "glob2>=0.7",
    "h5netcdf>=1.7.3",
    "h5py>=3.15.1",
    "hvplot>=0.12.2",
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "jupyter-lsp>=2.3.0",
    "jupyterlab>=4.5.1",
    "jupyterlab-code-formatter>=3.0.2",
    "libpysal>=4.13.0",
    "matplotlib>=3.10.8",
    "netcdf4>=1.7.3",
    "numpy==2.3.0",
    "pandas>=2.3.3",
    "pingouin>=0.5.5",
    "polars>=1.36.1",
    "pyarrow>=23.0.1",
    "python-lsp-server[all]>=1.14.0",
    "rasterio>=1.4.4",
    "rioxarray>=0.19.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.16.3",
    "seaborn>=0.13.2",
    "shap>=0.49.1",
    "shapely>=2.1.2",
    "statsmodels>=0.14.6",
    "tqdm>=4.67.1",
    "xarray>=2025.12.0",
]

[project.scripts]
dashboard = "gen_hack.dashboard:main"
